name: Postman Tests

on: [push]

jobs:
   run-postman-tests:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout Repository
       uses: actions/chekout@v4

     - name: Set up Node
       uses: actions/setup-node@v4
       with:
        node-version: '18'

     - name: Install newman
       uses: npm install -g newman

     - name: Run Postman API
       uses: newman run  

